[crate_roots]
rabbitholes = 'src'
tests = 'tests'
#  for the above (implementaiton) tests, use manager::manager::Manager, archive::archive::Archive, etc.
manager = 'src/manager/src'
rbits = 'src/rbits/src'
hole_registry = 'src/hole_registry/src'
rabbit_registry = 'src/rabbit_registry/src'
rabbit_storage = 'src/rabbit_storage/src'
# Testing
manager_testing = 'src/manager/tests'
rbits_testing = 'src/rbits/tests'
hole_registry_testing = 'src/hole_registry/tests'
rabbit_registry_testing = 'src/rabbit_registry/tests'
rabbit_storage_testing = 'src/rabbit_storage/tests'



