[crate_roots]
rabbitholes = 'src'
tests = 'tests'
#  for the above (implementaiton) tests, use manager::manager::Manager, archive::archive::Archive, etc.
rbits = 'src/rbits/src'
archive = 'src/archive/src'
manager = 'src/manager/src'
HoleRegistry = 'src/HoleRegistry/src'
# Testing
ManagerTesting = 'src/manager/tests'
ArchiveTesting = 'src/archive/tests'
RbitsTesting = 'src/rbits/tests'



