[crate_roots]
rabbitholes = 'src'
tests = 'tests'
#  for the above (implementaiton) tests, use manager::manager::Manager, archive::archive::Archive, etc.
rbits = 'src/rbits/src'
archive = 'src/archive/src'
manager = 'src/manager/src'
hole_registry = 'src/hole_registry/src'
RabbitRegistry = 'src/RabbitRegistry/src'
# Testing
ManagerTesting = 'src/manager/tests'
ArchiveTesting = 'src/archive/tests'
RbitsTesting = 'src/rbits/tests'
hole_registry_testing = 'src/hole_registry/tests'
RabbitRegistryTesting = 'src/RabbitRegistry/tests'



