[package]
name = "rabbitholes"
version = "0.1.0"

[dependencies]
# rbits = { path = "rbits" }
# manager = { path = "manager" }
# archive = { path = "archive" }

[scripts]
test = "cairo-test --starknet tests/lib.cairo"

