[[target.starknet-contract]]

[package]
name = "rabbitholes"
version = "0.1.0"
authors = ["Matt Carter <novemberfork@proton.me"]
readme = "README.md"
homepage = "https://novemberfork.io/"
repository = "https://github.com/0xDegenDeveloper/RabbitHoles"
description = "---"

[dependencies]
starknet = "2.0.0-rc6"
# sierra-compile = "starknet-sierra-compile src/lib.cairo sierra/rbits.json"
