# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest
[package]
name = "rabbitholes"
version = "0.1.0"

[dependencies]
starknet = "2.0.0-rc6"

[[target.starknet-contract]]

# [scripts]

# [cairo]
# sierra-replace-ids = true