[[target.starknet-contract]]

[lib]
casm = true

[package]
name = "RabbitRegistry"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

# [dependencies]
# foo = { path = "vendor/foo" }
